name: api_binance_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  get_it: ^8.0.3
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2

dev_dependencies:
  dio_adapter: ^2.1.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  http_mock_adapter: ^0.6.0
  test: any

flutter:
  uses-material-design: true
  generate: true